version: "3.9"

services:
  apps:
    build: ./apps           # Sesuaikan dengan lokasi Dockerfile Anda
    ports:
      - "10000:3000"
    restart: always
    env_file:
      - ./apps/.env         # Pastikan file .env ada di ./apps/.env
    volumes:
      - myapp:/usr/src/app  # Memetakan named volume "myapp" ke /usr/src/app di container

volumes:
  myapp:
